// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://kaomksywzvzmeqxsamjt.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imthb21rc3l3enZ6bWVxeHNhbWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4MjgwMTcsImV4cCI6MjA0NjQwNDAxN30.VC4kYAzqL99hC4mVyAKWEA0Fr-yftbrTmHsB8mmHe6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);